baseURL = "https://stoffie.github.io/"
languageCode = "en-us"
title = "stoffie.github.io"
theme = "github-style"

[params]
  author = "Damiano Stoffie"
  description = "Hello World!"
  github = "stoffie"
  email = "damstoffie@gmail.com"
  url = "https://stoffie.github.io"
  linkedin = "damiano-stoffie-109891164"
  keywords = "blog"
  rss = false
  lastmod = false
  favicon = "/images/github.png"
  location = "Italy. Pergine Valsugana TN"